### ISSUE TITLE
build failed with Xcode 15.4

### ISSUE THREAD

**Issue by command-not-found** [FiuuPayment/Mobile-XDK-Fiuu_Flutter#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 18.1

**Additional context**

<img width="663" alt="image" src="https://github.com/user-attachments/assets/89262fa0-fb27-4316-b496-cf872412362a">

**Comment by apis17** [comment]
hi @command-not-found, want to check this question already asked to telegram group? https://github.com/FiuuPayment/Telegram-FiuuDeveloperForum

**Comment by command-not-found** [comment]
Just update to the latest version
